image: "registry.gitlab.com/jbrazda/jb_test_ci"

stages:
  - backup
  - deploy 

  # Following Project Variables must be defined in th CI/CD Configuration
  # IICS_QA_ORG_USER: ""
  # IICS_QA_ORG_PWD: ""
  # IICS_PROD_ORG_USER: ""
  # IICS_PROD_ORG_PWD: ""
  # AWS_ACCESS_KEY_ID: "" 
  # AWS_SECRET_ACCESS_KEY: ""
  # AWS_DEFAULT_REGION: ""

variables:
  # QA Build Params
  IICS_QA_RELEASE_CONFIG: "./conf/iics.release.properties"
  IICS_QA_PACKAGE_CONFIG: "./conf/all_designs.package.txt"
  IICS_QA_TRANSFORM_CONFIG: "./conf/template.transform.properties"
  IICS_QA_PUBLISH_CONFIG: "./conf/all_designs.publish.txt"
  IICS_QA_EXPORT_PATH: "./target/iics/export/test"
  IICS_QA_EXPORT_FILE: "CI-CD-Demo"
  # PROD Build PARAMS
  IICS_PROD_RELEASE_CONFIG: "./conf/iics.release.properties"
  IICS_PROD_PACKAGE_CONFIG: "./conf/all_designs.package.txt"
  IICS_PROD_TRANSFORM_CONFIG: "./conf/template.transform.properties"
  IICS_PROD_PUBLISH_CONFIG: "./conf/all_designs.publish.txt"
  IICS_PROD_EXPORT_PATH: "./target/iics/export/prod"
  IICS_PROD_EXPORT_FILE: "CI-CD-Demo"
  AWS_S3_BUCKET: "s3://infa.cloud.in" 

backup-prod:
  stage: backup
  script: 
  - >
    ant download.src
    -Diics.user.prod="$IICS_PROD_ORG_USER"
    -Diics.password.prod="$IICS_PROD_ORG_PWD"
    -Diics.export.list.location=./conf/export_list.txt
    -Diics.release="$IICS_PROD_RELEASE_CONFIG"
    -Diics.source.environment="prod"
    -Dtools.reporting.disabled=true
  - build_time=$(date +"%Y-%m-%d-%H%M%S")
  - > 
    aws2 s3 cp
    "${IICS_PROD_EXPORT_PATH}/${IICS_PROD_EXPORT_FILE}.zip"
    "${AWS_S3_BUCKET}/${IICS_PROD_EXPORT_FILE}_${build_time}_${CI_COMMIT_SHORT_SHA}.zip"
  only:
    - master

backup-qa:
  stage: backup
  script: 
  - >
    ant download.src
    -Diics.user.test="$IICS_QA_ORG_USER"
    -Diics.password.test="$IICS_QA_ORG_PWD"
    -Diics.release="$IICS_QA_RELEASE_CONFIG"
    -Diics.export.list.location=./conf/export_list.txt
    -Diics.source.environment="test"
    -Dtools.reporting.disabled=true
  - build_time=$(date +"%Y-%m-%d-%H%M%S")
  - > 
    aws2 s3 cp
    "${IICS_QA_EXPORT_PATH}/${IICS_QA_EXPORT_FILE}.zip"
    "${AWS_S3_BUCKET}/${IICS_QA_EXPORT_FILE}_${build_time}_${CI_COMMIT_SHORT_SHA}.zip"
  only:
  - dev_qa_push

deploy-to-prod:
  stage: deploy 
  script:
  - > 
    ant build.deploy
    -Diics.user.prod="$IICS_PROD_ORG_USER"
    -Diics.password.prod="$IICS_PROD_ORG_PWD"
    -Diics.release="$IICS_PROD_RELEASE_CONFIG"
    -Diics.target.environment="prod"
    -Diics.target.package.config="$IICS_PROD_PACKAGE_CONFIG"
    -Diics.package.transform.config="$IICS_PROD_TRANSFORM_CONFIG"
    -Diics.target.publish.config="$IICS_PROD_PUBLISH_CONFIG"
    -Dtools.reporting.disabled=true
    -Dtools.transform.disabled=true
  only:
  - master


deploy-to-qa:
  stage: deploy
  script:
  - > 
    ant build.deploy
    -Diics.user.test="$IICS_QA_ORG_USER"
    -Diics.password.test="$IICS_QA_ORG_PWD"
    -Diics.release="$IICS_QA_RELEASE_CONFIG"
    -Diics.target.environment="test"
    -Diics.target.package.config="$IICS_QA_PACKAGE_CONFIG"
    -Diics.package.transform.config="$IICS_QA_TRANSFORM_CONFIG"
    -Diics.target.publish.config="$IICS_QA_PUBLISH_CONFIG"
    -Dtools.reporting.disabled=true
    -Dtools.transform.disabled=true
  only:
  - dev_qa_push
