# Manual  IICS Project Snapshot Pipeline
# @author: jbrazda@hcg.com
trigger:
- none
name: Automated IICS Snapshot (DEV)

variables:
- group: "IICS-CICD-DEV"

parameters:
  - name: commitMessage
    displayName: Commit Message
    type: string
    default: 'Automated IICS assets snapshot [skip_ci]'
  - name: updateBuildConfigs
    displayName: Update Build Configs
    type: boolean
    default: true


pool:
  vmImage: 'ubuntu-latest'
  demands: 
  - java

jobs: 

- job: Snapshot 
  condition: or(eq(variables['Build.SourceBranch'], 'dev'),contains(variables['Build.SourceBranch'],'features/'))
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "Build.SourceBranch:        $(Build.SourceBranch)"
      echo "Build.RequestedFor:        $(Build.RequestedFor)"
      echo "Build.RequestedForEmail:   $(Build.RequestedForEmail)"
      echo "Git Commit message:        ${{ parameters.commitMessage }}"
      echo "IICS_USER:                 $(IICS_ORG_USER)"
      echo '==========================================='
      echo 'ENV Variables'
      echo '==========================================='
      set
    displayName: 'Print Environment Info'
  # Export and Unzip Project assets from dev using ./conf/export_list.txt
  - task: Ant@1
    displayName: 'IICS Assets Snapshot'
    inputs:
      options: >-
        -Diics.user.dev=$(IICS_ORG_USER) 
        -Diics.password.dev=$(IICS_ORG_PWD) 
        -Diics.release=./conf/iics.release.properties 
        -Diics.source.environment=dev 
        -Diics.export.list.location=./conf/export_list.txt
      targets: 'clean.target clean.src update.src'
      buildFile: 'build.xml'
      publishJUnitResults: false
  # Update Build configurations based on the current content of the project assets
  - script: ./update_publish_all_config.sh
    displayName: 'Update Build Configurations'

  # On Windows use powershell script to generate the Build configs based on the current content of the project
  # - task: PowerShell@2
  #   inputs:
  #     filePath: 'update_build_configs.ps1'
  #   displayName: 'Update Build Configurations'
  #   condition: ${{ eq( parameters.updateBuildConfigs, true) }}

  - script: |
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global user.name "$(Build.RequestedFor)"
      git diff --stat
      git add .
      git commit -m "${{ parameters.commitMessage }}" 
      git push --set-upstream origin HEAD:$(Build.SourceBranch)
      echo "Git branch $(Build.SourceBranch) updated."
    displayName: 'Commit Updated Assets'