name: Deploy TEST Push
  # Following Project Secrets must be defined in the Repository/Environment Secrets for this Workflow
  # IICS_TEST_ORG_USER
  # IICS_TEST_ORG_PWD
  # AWS_ACCESS_KEY_ID
  # AWS_SECRET_ACCESS_KEY

on:
  # Trigger the workflow on push request,
  # but only for the defined branch
  # ignore changes to listed paths
  push:
    paths-ignore:
      - '.vscode/**'
      - '/doc/**'
      - '/sample-data/**'
      - '**.md'
      - '.ant_targets'
      - '.project'
      - 'update_publish_all_config.sh'
    branches:
      - push_test
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: test
    env:
      IICS_EXPORT_FILE: IICS_HCG_ClientName
      IICS_TARGET_ENVIRONMENT: test
      IICS_CONFIG_EXPORT: ./conf/export_list.txt 
      IICS_CONFIG_BACKUP: ./conf/all_exclude_connections.package.txt 
      IICS_CONFIG_PACKAGE: ./conf/push_dev_test.package.txt
      # Package Transformation config is optional, required when the IICS_PACKAGE_TRANSFORM_DISABLED = false
      IICS_CONFIG_TRANSFORM: ../../../conf/t2_test.transform.properties
      IICS_PACKAGE_TRANSFORM_DISABLED: false
      IICS_CONFIG_PUBLISH: ./conf/all_designs.publish.txt
      IICS_USER_NAME: ${{ secrets.IICS_TEST_ORG_USER }}
      IICS_USER_PWD: ${{ secrets.IICS_TEST_ORG_PWD }}
      # S3 Bucket for Target Org Asset Backup
      AWS_S3_BUCKET: "s3://infa.cloud.in/hcg"
    ## DO NOT EDIT STEPS BELOW UNLESS YOU WANT TO CHANGE THOSE, USE ENV VARIABLES ABOVE CONFIGURE THE BUILD
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.5.0
      with:
        distribution: zulu
        java-version: 11
      
    - name: Export Assets From Target Org
      run: |
        ant download.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.export.list.location=${{ env.IICS_CONFIG_EXPORT }} \
        -Diics.source.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Dtools.reporting.disabled=true
    - name: Package 
      run: |
        ant package.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=${{ env.IICS_CONFIG_BACKUP }} \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=${{ env.IICS_PACKAGE_TRANSFORM_DISABLED}}
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test_packages
        path: target/iics
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
    - name: Build Deploy
      run: |
        ant import publish \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=${{ env.IICS_CONFIG_PACKAGE }} \
        -Diics.target.publish.config=${{ env.IICS_CONFIG_PUBLISH }} \
        -Diics.package.transform.config=${{ env.IICS_CONFIG_TRANSFORM }} \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=${{ env.IICS_PACKAGE_TRANSFORM_DISABLED }}