# This is a basic workflow that is manually triggered

name: Manual Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# Following Project Secrets must be defined in the CI/CD Configuration
# IICS_DEV_ORG_USER: ""
# IICS_DEV_ORG_PWD: ""
# IICS_TEST_ORG_USER: ""
# IICS_TEST_ORG_PWD: ""
# IICS_PROD_ORG_USER: ""
# IICS_PROD_ORG_PWD: ""


on:
  workflow_dispatch:
    # Inputs the workflow accepts. use ${{ github.event.inputs.input_name }}
    inputs:
      package_config:
        # Override Custom Configuration
        description: 'Package Configuration'
        # Default value if no value is explicitly provided
        default: './conf/all_exclude_connections.package.txt'
        # Input has to be provided for the workflow to run
        required: true
      publish_config:
        # Override Custom Configuration
        description: 'Publish Configuration'
        # Default value if no value is explicitly provided
        default: './conf/all_designs.publish.txt'
        # Input has to be provided for the workflow to run
        required: true
      deploy_to:
        # Controls where to Deploy current revision build
        description: 'Deploy To Environment (comma separated list) Allowed Values: dev,test,prod'
        # Default value if no value is explicitly provided
        default: 'test,prod'
        # Input has to be provided for the workflow to run
        required: true
      
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      IICS_EXPORT_FILE: IICS_HCG_ClientName
      IICS_TARGET_ENVIRONMENT: dev
      IICS_USER_NAME: ${{ secrets.IICS_DEV_ORG_USER }}
      IICS_USER_PWD: ${{ secrets.IICS_DEV_ORG_PWD }}
    if: ${{ contains(github.event.inputs.deploy_to,'dev' ) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
      
    - name: Export Assets From Target Org
      run: |
        ant download.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.export.list.location=./conf/export_list.txt \
        -Diics.source.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Dtools.reporting.disabled=true
    - name: Package # Package current head for Archival
      run: |
        ant package.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=./conf/all_exclude_connections.package.txt \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dev_packages
        path: target/iics
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
    - name: Build Deploy
      run: |
        ant build.deploy \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=${{ github.event.inputs.package_config }} \
        -Diics.target.publish.config=${{ github.event.inputs.publish_config }}  \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true
  deploy_test:
    runs-on: ubuntu-latest
    environment: test
    env:
      IICS_EXPORT_FILE: IICS_HCG_ClientName
      IICS_TARGET_ENVIRONMENT: test
      IICS_USER_NAME: ${{ secrets.IICS_TEST_ORG_USER }}
      IICS_USER_PWD: ${{ secrets.IICS_TEST_ORG_PWD }}
    if: ${{ contains(github.event.inputs.deploy_to,'test' ) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
      
    - name: Export/Backup Assets From Target Org
      run: |
        ant download.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.export.list.location=./conf/export_list.txt \
        -Diics.source.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Dtools.reporting.disabled=true
    - name: Package # Package current head for Archival
      run: |
        ant package.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=./conf/all_exclude_connections.package.txt \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test_packages
        path: target/iics
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
    - name: Build Deploy
      run: |
        ant build.deploy \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=${{ github.event.inputs.package_config }} \
        -Diics.target.publish.config=${{ github.event.inputs.publish_config }} \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true
  deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      IICS_EXPORT_FILE: IICS_HCG_ClientName
      IICS_TARGET_ENVIRONMENT: prod
      IICS_USER_NAME: ${{ secrets.IICS_PROD_ORG_USER }}
      IICS_USER_PWD: ${{ secrets.IICS_PROD_ORG_PWD }}
    if: ${{ contains(github.event.inputs.deploy_to,'prod' ) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
      
    - name: Export Assets From Target Org
      run: |
        ant download.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.export.list.location=./conf/export_list.txt \
        -Diics.source.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Dtools.reporting.disabled=true
    - name: Package # Package current head for Archival
      run: |
        ant package.src \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=./conf/all_exclude_connections.package.txt \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: prod_packages
        path: target/iics
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
    - name: Build Deploy
      run: |
        ant build.deploy \
        -Diics.user.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_NAME }}" \
        -Diics.password.${{ env.IICS_TARGET_ENVIRONMENT }}="${{ env.IICS_USER_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.target.environment=${{ env.IICS_TARGET_ENVIRONMENT }} \
        -Diics.target.package.config=${{ github.event.inputs.package_config }} \
        -Diics.target.publish.config=${{ github.event.inputs.publish_config }} \
        -Dtools.reporting.disabled=true \
        -Dtools.transform.disabled=true