# This is a basic workflow that is manually triggered

name: Manual Dev Snapshot

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# Following Project Secrets must be defined in the CI/CD Configuration
# IICS_DEV_ORG_USER
# IICS_DEV_ORG_PWD

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commitMessage:
        # Custom commit message for commit snapshot
        description: 'Commit Message'
        # Default value if no value is explicitly provided
        default: 'IICS Dev Environment Snapshot'
        # Input has to be provided for the workflow to run
        type: string
        required: true


jobs:
  dev_commit_snapshot:
  #  Export IICS Assets from the environment
    runs-on: ubuntu-latest
    # only allow to snapshot into dev  or release branches
    if: ${{ github.head_ref == 'dev' || contains(github.ref,'releases') }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11 #java must be at least JDK 8 or newer, tested on jdk up to 11
    # - name: Cleanup old Sources
    #   # we need to cleanup old sources to handle renamed and deleted files
    #   # use ant clean.src instead
    #   run: |
    #     rm -rf ./src/iics
    - name: Print Environment Info
      run: |
        set
    - name: Export Project and Refresh From Source Org (DEV)
      env:
        IICS_SOURCE_ENVIRONMENT: dev
        # clean.src - We need to cleanup old sources to handle renamed and deleted files it deletes the src/iics content
        # update.src- task does export, expand and unzip nested archives to update src/iics design data
      run: |
        ant clean.src update.src \
        -Diics.user.${{ env.IICS_SOURCE_ENVIRONMENT }}="${{ secrets.IICS_DEV_ORG_USER }}" \
        -Diics.password.${{ env.IICS_SOURCE_ENVIRONMENT }}="${{ secrets.IICS_DEV_ORG_PWD }}" \
        -Diics.release=./conf/iics.release.properties \
        -Diics.export.list.location=./conf/export_list.txt \
        -Diics.source.environment=${{ env.IICS_SOURCE_ENVIRONMENT }} \
        -Dtools.reporting.disabled=true
    - name: Update Publish All Configuration
      run: ./update_publish_all_config.sh
    - name: Commit and Push Changes
      uses: actions-x/commit@v6
      with: # Push all changes back to current branch
        message: ${{ github.event.inputs.commitMessage }}
        branch: ${{ github.head_ref }}
        files: .